### ISSUE TITLE
'MODULE_NOT_FOUND' error when importing the package in marp

### ISSUE THREAD

**Issue by christophdebaene** [kazumatu981/markdown-it-fontawesome#1]
Hello, I use marp with `.mjs` and `.yml` file.
Note that using `@kazumatu981/markdown-it-kroki` works fine, but trying to import `@kazumatu981/markdown-it-fontawesome` gives the following error:

```
node:internal/modules/cjs/loader:1181
  const err = new Error(`Cannot find module '${request}'`);

Error: Cannot find module 'D:\slides\node_modules\markdown-it\lib\rules_block\list'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\\slides\node_modules\@kazumatu981\markdown-it-fontawesome\dist\lib\FaTagListRuleEngine.js:7:32)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\slides\\node_modules\\markdown-it\\package.json'
}
```

`.marprc.yml`

```yaml
allowLocalFiles: true
output: "./build"
inputDir: "./slides"
html: true
engine: "./engine.mjs"
template: bespoke
```

`engine.mjs`

```js
import markdownItKroki from '@kazumatu981/markdown-it-kroki';
import markdownItFontawesome from '@kazumatu981/markdown-it-fontawesome';

export default ({ marp }) => {
    
    marp
        .use(markdownItKroki)
        .use(markdownItFontawesome);
        
    return marp;
}
```

**Comment by kazumatu981** [comment]
I think this problem occurs when you use upper version of marp.
I will research more.
So please tell me the version number of marp, or please send me package.json, if you can.

**Comment by kazumatu981** [comment]
Thanks l will research more detail, please just moments.

**Comment by kazumatu981** [comment]
I also conducted a reproduction test here, but unfortunately, I couldn’t reproduce ERROR. Please check the attached file.

Another possible cause could be the version of Node.js, perhaps?
My Node.js version is 20.11.0 (little bit older than lts version....)

[tmp.zip](https://github.com/kazumatu981/markdown-it-fontawesome/files/14384552/tmp.zip)

**Comment by christophdebaene** [comment]
I had more dependencies in my `package.json` and `engine.mjs` and apparently that has an effect for getting the error.
I have included an updated version in the attached file. 
Now it should fail when you uncomment the `import` statement of `markdown-it-fontawesome`
  
[marp.zip](https://github.com/kazumatu981/markdown-it-fontawesome/files/14385939/marp.zip)

**Comment by kazumatu981** [comment]
Okey!!!!
I gocha!

Different your project and mine is  to use `@mdit/*` modules or not.
`@mdit/*` depends on `markdown-it` 14.0.0 but marp depends on 13.0.2.
So I must write this package depends on `markdown-it` 13 in `package.json`, but not to be written.

Anyway I'll upgrade as soon as possible.

**Comment by kazumatu981** [comment]
I fixed problem. It was different from the method I had in mind, but I managed to avoid the problem by reviewing the library dependencies.
Please upgrade to v1.0.4.

**Comment by christophdebaene** [comment]
Great, it's working now 👌
Thank you for your quick response and fix.
